POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "Warkoczewski",
  "emailAddress" : "adam.warkoczewski@training.pl"
}

###
GET http://localhost:8080/api/users/1
Accept: application/json

###


