version: '3'
services:
  database:
    image: postgres:13.2-alpine
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=nimda
      - PGDATA=/var/lib/postgresql/data/application
    volumes:
      - ../../../data:/var/lib/postgresql/data/application
  pgadmin:
    image: dpage/pgadmin4:4
    ports:
      - "8000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=awarkoczewski@yahoo.com
      - PGADMIN_DEFAULT_PASSWORD=admin

